"""add unique constraints to users

Revision ID: 5037aa06d0d1
Revises: e694aca4b295
Create Date: 2025-12-04 23:14:36.612493

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5037aa06d0d1"
down_revision: Union[str, None] = "e694aca4b295"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_emby_user_emby_id"), table_name="emby_user")
    op.create_index(op.f("ix_emby_user_emby_id"), "emby_user", ["emby_id"], unique=True)
    op.drop_index(op.f("ix_emby_user_tg_id"), table_name="emby_user")
    op.create_index(op.f("ix_emby_user_tg_id"), "emby_user", ["tg_id"], unique=True)
    op.drop_index(op.f("ix_plex_user_plex_email"), table_name="plex_user")
    op.create_index(
        op.f("ix_plex_user_plex_email"), "plex_user", ["plex_email"], unique=True
    )
    op.drop_index(op.f("ix_plex_user_plex_id"), table_name="plex_user")
    op.create_index(op.f("ix_plex_user_plex_id"), "plex_user", ["plex_id"], unique=True)
    op.drop_index(op.f("ix_plex_user_tg_id"), table_name="plex_user")
    op.create_index(op.f("ix_plex_user_tg_id"), "plex_user", ["tg_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_plex_user_tg_id"), table_name="plex_user")
    op.create_index(op.f("ix_plex_user_tg_id"), "plex_user", ["tg_id"], unique=False)
    op.drop_index(op.f("ix_plex_user_plex_id"), table_name="plex_user")
    op.create_index(
        op.f("ix_plex_user_plex_id"), "plex_user", ["plex_id"], unique=False
    )
    op.drop_index(op.f("ix_plex_user_plex_email"), table_name="plex_user")
    op.create_index(
        op.f("ix_plex_user_plex_email"), "plex_user", ["plex_email"], unique=False
    )
    op.drop_index(op.f("ix_emby_user_tg_id"), table_name="emby_user")
    op.create_index(op.f("ix_emby_user_tg_id"), "emby_user", ["tg_id"], unique=False)
    op.drop_index(op.f("ix_emby_user_emby_id"), table_name="emby_user")
    op.create_index(
        op.f("ix_emby_user_emby_id"), "emby_user", ["emby_id"], unique=False
    )
    # ### end Alembic commands ###
