"""add system_config table

Revision ID: f1a2b3c4d5e6
Revises: 5037aa06d0d1
Create Date: 2025-12-06 00:00:00.000000

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f1a2b3c4d5e6"
down_revision: Union[str, None] = "5037aa06d0d1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "system_config",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("config_type", sa.String(), nullable=False),
        sa.Column("config_key", sa.String(), nullable=False),
        sa.Column("config_value", sa.Text(), nullable=False),
        sa.Column("created_at", sa.BIGINT(), nullable=False),
        sa.Column("updated_at", sa.BIGINT(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("config_type", "config_key", name="uq_config_type_key"),
    )
    op.create_index(
        "idx_config_type_key",
        "system_config",
        ["config_type", "config_key"],
        unique=False,
    )
    op.create_index(
        op.f("ix_system_config_config_type"),
        "system_config",
        ["config_type"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_system_config_config_type"), table_name="system_config")
    op.drop_index("idx_config_type_key", table_name="system_config")
    op.drop_table("system_config")
    # ### end Alembic commands ###
