"""add line_schedule feature

Revision ID: g7h8i9j0k1l2
Revises: f1a2b3c4d5e6
Create Date: 2025-12-07 00:00:00.000000

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "g7h8i9j0k1l2"
down_revision: Union[str, None] = "f1a2b3c4d5e6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add line_schedule unlock fields to plex_user table
    op.add_column(
        "plex_user",
        sa.Column(
            "line_schedule_unlocked", sa.SMALLINT(), nullable=False, server_default="0"
        ),
    )
    op.add_column(
        "plex_user",
        sa.Column("line_schedule_unlock_time", sa.BIGINT(), nullable=True),
    )

    # Add line_schedule unlock fields to emby_user table
    op.add_column(
        "emby_user",
        sa.Column(
            "line_schedule_unlocked", sa.SMALLINT(), nullable=False, server_default="0"
        ),
    )
    op.add_column(
        "emby_user",
        sa.Column("line_schedule_unlock_time", sa.BIGINT(), nullable=True),
    )

    # Create line_schedule table
    op.create_table(
        "line_schedule",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("tg_id", sa.BIGINT(), nullable=False),
        sa.Column("service", sa.String(), nullable=False),
        sa.Column("line", sa.String(), nullable=False),
        sa.Column("days_of_week", sa.String(), nullable=False, server_default=""),
        sa.Column("start_time", sa.String(), nullable=False, server_default="00:00"),
        sa.Column("end_time", sa.String(), nullable=False, server_default="00:00"),
        sa.Column("priority", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("is_enabled", sa.SMALLINT(), nullable=False, server_default="1"),
        sa.Column("is_default", sa.SMALLINT(), nullable=False, server_default="0"),
        sa.Column("created_at", sa.BIGINT(), nullable=False),
        sa.Column("updated_at", sa.BIGINT(), nullable=False),
        sa.CheckConstraint("service IN ('plex', 'emby')", name="ck_schedule_service"),
        sa.CheckConstraint("is_enabled IN (0, 1)", name="ck_schedule_enabled"),
        sa.CheckConstraint("is_default IN (0, 1)", name="ck_schedule_is_default"),
        sa.ForeignKeyConstraint(
            ["tg_id"],
            ["statistics.tg_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_schedule_user_service", "line_schedule", ["tg_id", "service"], unique=False
    )
    op.create_index(
        "idx_schedule_user_service_enabled",
        "line_schedule",
        ["tg_id", "service", "is_enabled"],
        unique=False,
    )
    op.create_index(
        "idx_schedule_user_service_default",
        "line_schedule",
        ["tg_id", "service", "is_default"],
        unique=False,
    )
    op.create_index(
        op.f("ix_line_schedule_tg_id"), "line_schedule", ["tg_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_line_schedule_tg_id"), table_name="line_schedule")
    op.drop_index("idx_schedule_user_service_default", table_name="line_schedule")
    op.drop_index("idx_schedule_user_service_enabled", table_name="line_schedule")
    op.drop_index("idx_schedule_user_service", table_name="line_schedule")
    op.drop_table("line_schedule")

    op.drop_column("emby_user", "line_schedule_unlock_time")
    op.drop_column("emby_user", "line_schedule_unlocked")
    op.drop_column("plex_user", "line_schedule_unlock_time")
    op.drop_column("plex_user", "line_schedule_unlocked")
    # ### end Alembic commands ###
